name: flutter_button_counter
description: A simple counter app to demonstrate widget vs integration testing.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"   # ✅ Compatible with Dart 3.2.3 in GitHub Actions
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true