name: Flutter Tests (no web)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Disable web support (prevent web device usage)
        run: flutter config --no-enable-web

      - name: Clean previous builds
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run Widget Tests
        run: flutter test test/

      - name: Run Integration Tests (headless)
        run: flutter test integration_test/
        env:
          DISPLAY: ":99"