name: Flutter Tests (Headless on Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Widget & Integration Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Clean previous builds
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Run Widget Tests
        run: flutter test test/

      - name: Run Integration Tests (Headless on Linux)
        run: flutter test integration_test/