name: Flutter Tests (Headless CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter-test:
    name: Run Widget & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Disable Web (avoid device conflicts)
        run: flutter config --no-enable-web

      - name: Clean Project
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Widget Tests
        run: flutter test test/
        env:
          ENABLE_FLUTTER_DESKTOP: false  # ⛔ Avoid Linux GUI build

      - name: Run Integration Tests (Headless)
        run: flutter test integration_test/
        env:
          ENABLE_FLUTTER_DESKTOP: false  # ⛔ Prevent Linux build & CMake errors