name: Flutter iOS Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-integration-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Install dependencies
        run: flutter pub get

      - name: Prebuild iOS (to install pods)
        run: flutter build ios --simulator --no-codesign

      - name: Run integration test on iOS simulator
        run: |
          xcrun simctl boot "iPhone 14"
          open -a Simulator
          flutter drive \
            --target=integration_test/app_test.dart \
            --driver=test_driver/integration_test.dart \
            -d "iPhone 14"