name: Flutter Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Run Android Emulator and Integration Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: |
            adb devices
            adb wait-for-device
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
          disable-animations: true
          working-directory: .
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim
          script-timeout-minutes: 10