name: Flutter Tests (Widget + App + Integration)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter-tests:
    name: Run Widget & App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Disable Web and Desktop
        run: |
          flutter config --no-enable-web
          flutter config --no-enable-linux-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Widget Tests
        run: flutter test test/widget_test.dart

      - name: Run App Tests
        run: flutter test test/app_test.dart

  integration-test:
    name: Run Integration Test on Android Emulator
    runs-on: ubuntu-latest
    needs: flutter-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Run Android Emulator and Integration Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -no-audio -no-boot-anim -accel off
          disable-animations: true
          pre-emulator-launch-script: |
            echo "Resetting ADB and waiting for emulator..."
            adb kill-server || true
            sleep 5
            adb start-server
            sleep 15
          script: |
            adb wait-for-device
            boot_complete=""
            until [[ "$boot_complete" == "1" ]]; do
              boot_complete=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
              echo "boot_complete=$boot_complete"
              sleep 5
            done
            echo "Emulator ready."

            flutter pub get
            flutter drive \
              --driver=test_driver/integration_test.dart \
              --target=integration_test/app_test.dart